### ISSUE TITLE
Typo in Twitter handle

### ISSUE THREAD

**Issue by ivanstegic** [amandeepmittal/gatsby-bulma-quickstart#2]
I think the handle on this page should be @amanhimself not @amahimself

https://github.com/amandeepmittal/gatsby-bulma-quickstart/blob/967bb01c304845b97fb971c7b692b123bb1ac397/src/components/footer.js#L30

**Comment by amandeepmittal** [comment]
Hey @ivanstegic much thanks for pointing this out 👏 👏 👏
I am fixing it right now.
